### ISSUE TITLE
petition to add yq

### ISSUE THREAD

**Issue by bryanwieg** [budimanjojo/kubernetes-toolbox#154]
Hello @budimanjojo ,

I came across your k8s docker toolbox. We have found it useful for some of our pipelines.

How would you feel about adding yq to the image?

There are various ways, but the most reliable i have found is via apk:

```bash
apk add yq --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
```

If it is something you approve of, I'd be happy to submit a pr if needed.

Thanks,
Bryan

PS To clarify, we are using yq to lint and update k8s yaml manifests.

**Comment by budimanjojo** [comment]
Hello, Bryan! Feel free to create the PR and I'll merge it. :)

**Comment by bryanwieg** [comment]
a pr is up at #155

**Comment by bryanwieg** [comment]
thank you!
